### ISSUE TITLE
[REQ] add a (GH-compliant) license file

### ISSUE THREAD

**Issue by forart** [Max13245/DRC#1]
Hi there, 1st of all thanks for this cool work !

Since we've "doxed" it in our [HyMPS project](https://github.com/forart/HyMPS#readme) (under the [AUDIO](https://github.com/forart/HyMPS#-) \ [AI-based page](https://github.com/forart/HyMPS/blob/main/AIaudio.md#--) \ [Misc subsection](https://github.com/forart/HyMPS/blob/main/AIaudio.md#misc-)), can you please add a "GH-compliant" license file ?

Expliciting licensing terms is extremely important to let other devs (and not only) understand how to reuse/adapt/modify your code in other open projects and vice-versa.

Although it may sounds like a minor aspect, license file omission obviously causes an inconsistent generation of the relative badge too:

![](https://flat.badgen.net/github/license/Max13245/DRC/?label=LICENSE)
(badge-generator URL: https://flat.badgen.net/github/license/Max13245/DRC/?label=LICENSE)

Anyway you can easily set a "compliant" one through the GH's license wizard tool.

Last but not least, let us know how - in your opinion - we could improve categorization/sorting of collected projects in order to push their evolution by favouring collaborations between developers (and not only).

Thanks in advance.

**Comment by Max13245** [comment]
Hello, 

This was part of a school project, I just put it online for my supervisor. 
It doesn't work, maybe it could, we didn't have enough time left to find out and thus it was never finished. Also it's kind of a mess. 

I was planning to set this repo back to private, however if you still think this is actually useful I will leave it public. 
Let me know, bye.

**Comment by forart** [comment]
Hi there, thanks for reply.

Every open source code can be useful for other devs (even as mere inspiration) ! 
Anyway, if you've already decided to shut down the project, our suggestion is to set the license and make the git as public archive.

However, as mentioned above, let us know how - if you like - how we can improve our resources collection.

Thanks again.

**Comment by Max13245** [comment]
Alright I have licensed it. Hope it helps!
